In [1]:
import numpy as np
import sys

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0.5, 1, 1.5, 2])

In [5]:
a[0]

1

In [6]:
a[0:3]

array([1, 2, 3])

In [7]:
b[1:]

array([1. , 1.5, 2. ])

In [8]:
a[::2]

array([1, 3])

In [9]:
b[0], b[1], b[-1]

(0.5, 1.0, 2.0)

In [10]:
b[[0, 2, -1]]

array([0.5, 1.5, 2. ])

Array Types

In [11]:
a

array([1, 2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [13]:
b.dtype

dtype('float64')

In [14]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [15]:
c = np.array(['a', 'b', 'c'])

In [16]:
c

array(['a', 'b', 'c'], dtype='<U1')

In [17]:
d = np.array([{'a': 1}, sys])

In [18]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

Dimensions and Shape

In [19]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [20]:
A.shape

(3, 3)

In [21]:
A.size

9

In [22]:
A.ndim

2

In [23]:
B = np.array([
  [
    [12,11,10], [9,8,7]
  ],
  [
    [6,5,4], [3,2,1]
  ]
  ])

In [24]:
B.shape

(2, 2, 3)

In [25]:
B.shape

(2, 2, 3)

In [26]:
B.size

12

In [27]:
B.ndim

3

Indexing and Slicing of Matrices

In [28]:
#A[d1, d2, d3, d4]
A[1]

array([4, 5, 6])

In [29]:
A[1][0]

4

In [30]:
A[0: 2]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [32]:
A[1] = np.array([10,10,10])

In [33]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [34]:
A[2] = 99

In [35]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary statictics

In [36]:
a = np.array([1,2,3,4])

In [37]:
a.sum()

10

In [38]:
a.mean()

2.5

In [39]:
a.std()

1.118033988749895

In [40]:
a.var()

1.25

In [41]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [42]:
A.sum()

45

In [43]:
A.mean()

5.0

In [44]:
# Row Level
A.sum(axis=0)

array([12, 15, 18])

In [45]:
#Column Level
A.sum(axis=1)

array([ 6, 15, 24])

Braodcasting and Vectorized Operations

In [46]:
a = np.arange(4)

In [47]:
a

array([0, 1, 2, 3])

In [48]:
a + 10

array([10, 11, 12, 13])

In [49]:
a * 10

array([ 0, 10, 20, 30])

In [50]:
a

array([0, 1, 2, 3])

In [51]:
a += 100

In [52]:
a

array([100, 101, 102, 103])

In [53]:
l = [0, 1, 2, 3]

In [54]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [55]:
b = np.arange(4)

In [56]:
a + b 

array([100, 102, 104, 106])

In [57]:
a * b

array([  0, 101, 204, 309])

Boolean Arrays

In [66]:
c = np.arange(5)

In [67]:
c

array([0, 1, 2, 3, 4])

In [70]:
c[[True, False, True, False, True]]

array([0, 2, 4])

In [71]:
c >=2

array([False, False,  True,  True,  True])

In [72]:
c[c >= 2]

array([2, 3, 4])

In [73]:
c.mean()

2.0

In [74]:
c[c > c.mean()]

array([3, 4])

In [75]:
c[(c == 0) | (c == 1)]

array([0, 1])

In [77]:
c[(c <= 2) & (c % 2 ==0)]

array([0, 2])

In [78]:
A = np.random.randint(100, size=(3,3))

In [79]:
A

array([[ 0, 30, 29],
       [69, 20, 10],
       [91, 54, 17]])

In [80]:
A > 30

array([[False, False, False],
       [ True, False, False],
       [ True,  True, False]])

In [81]:
A [A > 30]

array([69, 91, 54])

Numpy Algebra and Size

In [86]:
A

array([[ 0, 30, 29],
       [69, 20, 10],
       [91, 54, 17]])

In [83]:
B = np.random.randint(10, size=(3,2))
B

array([[7, 6],
       [4, 9],
       [5, 3]])

In [84]:
A.dot(B)

array([[ 265,  357],
       [ 613,  624],
       [ 938, 1083]])

In [87]:
A @ B

array([[ 265,  357],
       [ 613,  624],
       [ 938, 1083]])

In [85]:
B.T

array([[7, 4, 5],
       [6, 9, 3]])

In [88]:
B.T @ A

array([[731, 560, 328],
       [894, 522, 315]])

Size of Objects in Memory

In [90]:
#An integer in python is > 24bytes
sys.getsizeof(1)

28

In [91]:
sys.getsizeof(10**100)

72

In [92]:
#Numpy size is much smaller
np.dtype(int).itemsize

4

In [93]:
np.dtype(float).itemsize

8

Lists are even Larger

In [94]:
sys.getsizeof([1])

64

In [95]:
np.array([1]).nbytes

4

Performance is also important

In [145]:
l = list(range(100000))

In [146]:
d = np.arange(100000)

In [147]:
%time np.sum(d ** 2)

CPU times: total: 0 ns
Wall time: 1.01 ms


216474736

In [148]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 14 ms


333328333350000