In [8]:
import numpy as np
import sys

In [9]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [10]:
a = np.array([1,2,3,4])

In [11]:
b = np.array([0.5, 1, 1.5, 2])

In [12]:
a[0]

1

In [13]:
a[0:3]

array([1, 2, 3])

In [14]:
b[1:]

array([1. , 1.5, 2. ])

In [15]:
a[::2]

array([1, 3])

In [16]:
b[0], b[1], b[-1]

(0.5, 1.0, 2.0)

In [20]:
b[[0, 2, -1]]

array([0.5, 1.5, 2. ])

Array Types

In [17]:
a

array([1, 2, 3, 4])

In [18]:
a.dtype

dtype('int32')

In [19]:
b.dtype

dtype('float64')

In [21]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [23]:
c = np.array(['a', 'b', 'c'])

In [24]:
c

array(['a', 'b', 'c'], dtype='<U1')

In [25]:
d = np.array([{'a': 1}, sys])

In [26]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

Dimensions and Shape

In [39]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [40]:
A.shape

(3, 3)

In [41]:
A.size

9

In [42]:
A.ndim

2

In [43]:
B = np.array([
  [
    [12,11,10], [9,8,7]
  ],
  [
    [6,5,4], [3,2,1]
  ]
  ])

In [44]:
B.shape

(2, 2, 3)

In [45]:
B.shape

(2, 2, 3)

In [46]:
B.size

12

In [47]:
B.ndim

3

Indexing and Slicing of Matrices

In [52]:
#A[d1, d2, d3, d4]
A[1]

array([4, 5, 6])

In [53]:
A[1][0]

4

In [54]:
A[0: 2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [56]:
A[1] = np.array([10,10,10])

In [57]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [58]:
A[2] = 99

In [59]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary statictics

In [60]:
a = np.array([1,2,3,4])

In [61]:
a.sum()

10

In [63]:
a.mean()

2.5

In [64]:
a.std()

1.118033988749895

In [65]:
a.var()

1.25

In [67]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [68]:
A.sum()

45

In [69]:
A.mean()

5.0

In [70]:
# Row Level
A.sum(axis=0)

array([12, 15, 18])

In [71]:
#Column Level
A.sum(axis=1)

array([ 6, 15, 24])