Initializing diff types of arrays

In [1]:
import numpy as np
import pandas as pd


In [4]:
#All 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [6]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [7]:
#Any other type
np.full((2,2), 99, dtype='float64')

array([[99., 99.],
       [99., 99.]])

In [8]:
#Random decimal Numbers
np.random.rand(4,2)

array([[0.67422621, 0.2648077 ],
       [0.29200752, 0.27071143],
       [0.99761496, 0.5309295 ],
       [0.86266279, 0.97281098]])

In [9]:
#Random integer Numbers
np.random.randint(4, 7, size=(3,3))

array([[6, 4, 6],
       [6, 4, 5],
       [4, 4, 6]])

In [10]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
output = np.ones((5,5))
output

z = np.zeros((3,3))
z[1,1] = 9
z

output[1:4, 1:4] = z #you can also use -1 instead of 4
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Be careful when copying arrays

In [18]:
a = np.array([1,2,3])
b = a
b[0] = 100
b

array([100,   2,   3])

In [23]:
c = np.array([1,2,3])
d = c.copy()
c[0] = 100
d

array([1, 2, 3])

<h2> Mathematics

In [24]:
a = np.array([1,2,3,4])

In [25]:
a +3

array([4, 5, 6, 7])

In [26]:
a - 4 

array([-3, -2, -1,  0])

In [27]:
a * 2 

array([2, 4, 6, 8])

In [28]:
a / 4

array([0.25, 0.5 , 0.75, 1.  ])

In [29]:
a ** 2 

array([ 1,  4,  9, 16])

In [30]:
b = np.array([2,2,4,5])

In [31]:
a + b

array([3, 4, 7, 9])

<h3> Linear Algebra

In [33]:
a = np.ones((2,3))
a

b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [34]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [35]:
#Find the determinent
c = np.identity(3)
np.linalg.det(c)

1.0

<h3> Statistics

In [37]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.min(stats, axis=1)

array([1, 4])

In [44]:
np.max(stats, axis=0)

array([4, 5, 6])

<h3> Reorganizing Arrays

In [46]:
before = np.array([[1,2,3,4], [5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
#Vertically stacking Matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
a = np.ones((2, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<h3> Laading Data and Advanced Indexing

In [54]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')

array([ 1, 15, 14, 78, 96, 78, 25, 14,  3, 25, 96, 61, 58, 74, 15, 26, 34,
       14, 75])

Boolean masking and advanced indexing

In [56]:
filedata[filedata > 50]

array([78., 96., 78., 96., 61., 58., 74., 75.])

In [59]:

a = np.array([1,2,3,4,5,6,7,8,9])

In [60]:
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
# np.any | np.all
