In [1]:
import numpy as np
import sys

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0.5, 1, 1.5, 2])

In [5]:
a[0]

1

In [6]:
a[0:3]

array([1, 2, 3])

In [7]:
b[1:]

array([1. , 1.5, 2. ])

In [8]:
a[::2]

array([1, 3])

In [9]:
b[0], b[1], b[-1]

(0.5, 1.0, 2.0)

In [10]:
b[[0, 2, -1]]

array([0.5, 1.5, 2. ])

Array Types

In [11]:
a

array([1, 2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [13]:
b.dtype

dtype('float64')

In [14]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [15]:
c = np.array(['a', 'b', 'c'])

In [16]:
c

array(['a', 'b', 'c'], dtype='<U1')

In [17]:
d = np.array([{'a': 1}, sys])

In [18]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

Dimensions and Shape

In [19]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [20]:
A.shape

(3, 3)

In [21]:
A.size

9

In [22]:
A.ndim

2

In [23]:
B = np.array([
  [
    [12,11,10], [9,8,7]
  ],
  [
    [6,5,4], [3,2,1]
  ]
  ])

In [24]:
B.shape

(2, 2, 3)

In [25]:
B.shape

(2, 2, 3)

In [26]:
B.size

12

In [27]:
B.ndim

3

Indexing and Slicing of Matrices

In [28]:
#A[d1, d2, d3, d4]
A[1]

array([4, 5, 6])

In [29]:
A[1][0]

4

In [30]:
A[0: 2]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [32]:
A[1] = np.array([10,10,10])

In [33]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [34]:
A[2] = 99

In [35]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary statictics

In [36]:
a = np.array([1,2,3,4])

In [37]:
a.sum()

10

In [38]:
a.mean()

2.5

In [39]:
a.std()

1.118033988749895

In [40]:
a.var()

1.25

In [41]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [42]:
A.sum()

45

In [43]:
A.mean()

5.0

In [44]:
# Row Level
A.sum(axis=0)

array([12, 15, 18])

In [45]:
#Column Level
A.sum(axis=1)

array([ 6, 15, 24])

Braodcasting and Vectorized Operations

In [46]:
a = np.arange(4)

In [47]:
a

array([0, 1, 2, 3])

In [48]:
a + 10

array([10, 11, 12, 13])

In [49]:
a * 10

array([ 0, 10, 20, 30])

In [50]:
a

array([0, 1, 2, 3])

In [51]:
a += 100

In [52]:
a

array([100, 101, 102, 103])

In [53]:
l = [0, 1, 2, 3]

In [54]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [55]:
b = np.arange(4)

In [56]:
a + b 

array([100, 102, 104, 106])

In [57]:
a * b

array([  0, 101, 204, 309])

Boolean Arrays

In [58]:
c = np.arange(5)

In [59]:
c

array([0, 1, 2, 3, 4])

In [60]:
c[[True, False, True, False, True]]

array([0, 2, 4])

In [61]:
c >=2

array([False, False,  True,  True,  True])

In [62]:
c[c >= 2]

array([2, 3, 4])

In [63]:
c.mean()

2.0

In [64]:
c[c > c.mean()]

array([3, 4])

In [65]:
c[(c == 0) | (c == 1)]

array([0, 1])

In [66]:
c[(c <= 2) & (c % 2 ==0)]

array([0, 2])

In [67]:
A = np.random.randint(100, size=(3,3))

In [68]:
A

array([[83, 80, 91],
       [96, 64, 80],
       [13, 78, 63]])

In [69]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [70]:
A [A > 30]

array([83, 80, 91, 96, 64, 80, 78, 63])

Numpy Algebra and Size

In [71]:
A

array([[83, 80, 91],
       [96, 64, 80],
       [13, 78, 63]])

In [72]:
B = np.random.randint(10, size=(3,2))
B

array([[9, 8],
       [2, 4],
       [4, 6]])

In [73]:
A.dot(B)

array([[1271, 1530],
       [1312, 1504],
       [ 525,  794]])

In [74]:
A @ B

array([[1271, 1530],
       [1312, 1504],
       [ 525,  794]])

In [75]:
B.T

array([[9, 2, 4],
       [8, 4, 6]])

In [76]:
B.T @ A

array([[ 991, 1160, 1231],
       [1126, 1364, 1426]])

Size of Objects in Memory

In [77]:
#An integer in python is > 24bytes
sys.getsizeof(1)

28

In [78]:
sys.getsizeof(10**100)

72

In [79]:
#Numpy size is much smaller
np.dtype(int).itemsize

4

In [80]:
np.dtype(float).itemsize

8

Lists are even Larger

In [81]:
sys.getsizeof([1])

64

In [82]:
np.array([1]).nbytes

4

Performance is also important

In [83]:
l = list(range(100000))

In [84]:
d = np.arange(100000)

In [85]:
%time np.sum(d ** 2)

CPU times: total: 0 ns
Wall time: 1 ms


216474736

In [86]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 23 ms


333328333350000

<h1> Pandas Library </h1>

In [87]:
import pandas as pd

In [88]:
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])

In [89]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

In [90]:
g7_pop.name = 'G7 Population in millions'

In [91]:
g7_pop.dtype

dtype('float64')

In [92]:
g7_pop.values

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 318.523])

In [93]:
g7_pop[2]

80.94

In [94]:
g7_pop.index

RangeIndex(start=0, stop=7, step=1)

In [95]:
g7_pop.index = ['Canada', 'France', 'Germany', 'Italy', 'Japan', 'UK', 'USA']

In [96]:
g7_pop

Canada      35.467
France      63.951
Germany     80.940
Italy       60.665
Japan      127.061
UK          64.511
USA        318.523
Name: G7 Population in millions, dtype: float64

In [97]:
g7_pop['Canada']

35.467

In [98]:
g7_pop['Japan']

127.061

In [99]:
g7_pop.iloc[0]

35.467

In [100]:
g7_pop.iloc[-1]

318.523

In [101]:
g7_pop[['France', 'Italy']]

France    63.951
Italy     60.665
Name: G7 Population in millions, dtype: float64

In [102]:
#Last Item Is included in Pandas
g7_pop['Canada': 'Italy']

Canada     35.467
France     63.951
Germany    80.940
Italy      60.665
Name: G7 Population in millions, dtype: float64

Conditional Selection (Boolean Arrays)

In [103]:
g7_pop > 70

Canada     False
France     False
Germany     True
Italy      False
Japan       True
UK         False
USA         True
Name: G7 Population in millions, dtype: bool

In [104]:
g7_pop[g7_pop > 70]

Germany     80.940
Japan      127.061
USA        318.523
Name: G7 Population in millions, dtype: float64

In [105]:
g7_pop.mean()

107.30257142857144

In [106]:
g7_pop[g7_pop > g7_pop.mean()]

Japan    127.061
USA      318.523
Name: G7 Population in millions, dtype: float64

In [107]:
g7_pop.std()

97.24996987121581

In [108]:
g7_pop[(g7_pop > g7_pop.mean() - g7_pop.std() / 2) | (g7_pop > g7_pop.mean() + g7_pop.std() / 2)]

France      63.951
Germany     80.940
Italy       60.665
Japan      127.061
UK          64.511
USA        318.523
Name: G7 Population in millions, dtype: float64

Operations and Methods

In [109]:
g7_pop

Canada      35.467
France      63.951
Germany     80.940
Italy       60.665
Japan      127.061
UK          64.511
USA        318.523
Name: G7 Population in millions, dtype: float64

In [110]:
g7_pop * 1000

Canada      35467.0
France      63951.0
Germany     80940.0
Italy       60665.0
Japan      127061.0
UK          64511.0
USA        318523.0
Name: G7 Population in millions, dtype: float64

Modifying Series

In [111]:
#Direct Indexing
g7_pop['Canada'] = 40.5

In [112]:
g7_pop

Canada      40.500
France      63.951
Germany     80.940
Italy       60.665
Japan      127.061
UK          64.511
USA        318.523
Name: G7 Population in millions, dtype: float64

In [113]:
#Boolean Indexing
g7_pop[g7_pop < 70] = 99.99

In [114]:
g7_pop

Canada      99.990
France      99.990
Germany     80.940
Italy       99.990
Japan      127.061
UK          99.990
USA        318.523
Name: G7 Population in millions, dtype: float64

<h2> DataFrames

In [115]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])

In [116]:
df

Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [117]:
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [118]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Population    7 non-null      float64
 1   GDP           7 non-null      int64  
 2   Surface Area  7 non-null      int64  
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object 
dtypes: float64(2), int64(2), object(1)
memory usage: 336.0+ bytes


In [120]:
df.size

35

In [121]:
df.shape

(7, 5)

In [122]:
df.describe()

Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [123]:
df.dtypes


Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [124]:
df.dtypes.value_counts()

float64    2
int64      2
object     1
Name: count, dtype: int64

Indexing, Selection and Slicing


In [125]:
df.loc['Canada']

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [126]:
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [127]:
df['Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [128]:
df['GDP']

Canada             1785387
France             2833687
Germany            3874437
Italy              2167744
Japan              4602367
United Kingdom     2950039
United States     17348075
Name: GDP, dtype: int64

In [129]:
df[['Population', 'GDP']]

Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [130]:
df[1:3]

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

In [131]:
df.loc['France': 'Italy']

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

In [132]:
df.loc['France': 'Italy', 'Population']

France     63.951
Germany    80.940
Italy      60.665
Name: Population, dtype: float64

In [133]:
df.loc['France': 'Italy', ['Population', 'GDP']]

Population      GDP
France       63.951  2833687
Germany      80.940  3874437
Italy        60.665  2167744

In [134]:
df.iloc[0]

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [135]:
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [136]:
df.iloc[[0, 1, -1]]

Population       GDP  Surface Area    HDI Continent
Canada             35.467   1785387       9984670  0.913   America
France             63.951   2833687        640679  0.888    Europe
United States     318.523  17348075       9525067  0.915   America

In [137]:
df.iloc[1:3]

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

In [138]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [139]:
df.iloc[1:3, [0, 3]]

Population    HDI
France       63.951  0.888
Germany      80.940  0.916

In [140]:
df.iloc[1:3, 1:3]

GDP  Surface Area
France   2833687        640679
Germany  3874437        357114

In [141]:
certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})
certificates_earned

Certificates  Time (in months)
0             8                16
1             2                 5
2             5                 9
3             6                12

In [142]:
certificates_earned.index = ['Tom', 'Kris', 'Ahmad', 'Beau']

In [143]:
certificates_earned

Certificates  Time (in months)
Tom               8                16
Kris              2                 5
Ahmad             5                 9
Beau              6                12

In [144]:
df['Population'] > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [145]:
df.loc[df['Population'] > 70, 'Population']

Germany           80.940
Japan            127.061
United States    318.523
Name: Population, dtype: float64

In [146]:
df.loc[df['Population'] > 70, ['Population', 'GDP']]

Population       GDP
Germany            80.940   3874437
Japan             127.061   4602367
United States     318.523  17348075

Dropping Stuff

In [147]:
df.drop('Canada')

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [148]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [149]:
df.drop(['Canada', 'Japan'])

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [150]:
df.drop(columns=['Population', 'HDI'])

GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [151]:
df.drop(['Italy', 'Canada'], axis=0)

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

<h3> Operations

In [152]:
crisis = pd.Series([-1_000_000, -0.3], index=['GDP', 'HDI'])
crisis

GDP   -1000000.0
HDI         -0.3
dtype: float64

In [153]:
df[['GDP', 'HDI']] + crisis

GDP    HDI
Canada            785387.0  0.613
France           1833687.0  0.588
Germany          2874437.0  0.616
Italy            1167744.0  0.573
Japan            3602367.0  0.591
United Kingdom   1950039.0  0.607
United States   16348075.0  0.615

<h3> Modifying DataFrames

In [154]:
langs = pd.Series(
    ['French', 'German', 'Italian'],
    index=['France', 'Germany', 'Italy'],
    name='Language'
)
langs

France      French
Germany     German
Italy      Italian
Name: Language, dtype: object

In [155]:
df['Language'] = langs
df

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
United States      318.523  17348075       9525067  0.915   America      NaN

In [156]:
df['Language'] = 'English'
df

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America  English
France              63.951   2833687        640679  0.888    Europe  English
Germany             80.940   3874437        357114  0.916    Europe  English
Italy               60.665   2167744        301336  0.873    Europe  English
Japan              127.061   4602367        377930  0.891      Asia  English
United Kingdom      64.511   2950039        242495  0.907    Europe  English
United States      318.523  17348075       9525067  0.915   America  English

In [157]:
df.rename(
    columns={
        'HDI': 'Human Development Index',
        'Anual Popcorn Consumption': 'APC'
    }, index={
        'United States': 'USA',
        'United Kingdom': 'UK',
        'Argentina': 'AR'
    })

Population       GDP  Surface Area  Human Development Index  \
Canada       35.467   1785387       9984670                    0.913   
France       63.951   2833687        640679                    0.888   
Germany      80.940   3874437        357114                    0.916   
Italy        60.665   2167744        301336                    0.873   
Japan       127.061   4602367        377930                    0.891   
UK           64.511   2950039        242495                    0.907   
USA         318.523  17348075       9525067                    0.915   

        Continent Language  
Canada    America  English  
France     Europe  English  
Germany    Europe  English  
Italy      Europe  English  
Japan        Asia  English  
UK         Europe  English  
USA       America  English

In [158]:
df.rename(index=str.upper)

Population       GDP  Surface Area    HDI Continent Language
CANADA              35.467   1785387       9984670  0.913   America  English
FRANCE              63.951   2833687        640679  0.888    Europe  English
GERMANY             80.940   3874437        357114  0.916    Europe  English
ITALY               60.665   2167744        301336  0.873    Europe  English
JAPAN              127.061   4602367        377930  0.891      Asia  English
UNITED KINGDOM      64.511   2950039        242495  0.907    Europe  English
UNITED STATES      318.523  17348075       9525067  0.915   America  English

In [159]:
df

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America  English
France              63.951   2833687        640679  0.888    Europe  English
Germany             80.940   3874437        357114  0.916    Europe  English
Italy               60.665   2167744        301336  0.873    Europe  English
Japan              127.061   4602367        377930  0.891      Asia  English
United Kingdom      64.511   2950039        242495  0.907    Europe  English
United States      318.523  17348075       9525067  0.915   America  English

<h3> Dropping Columns

In [160]:
df.drop(columns='Language', inplace=True)

In [161]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

Adding values

In [162]:
pd.concat([df, pd.Series({
    'Population': 3,
    'GDP': 5
}, name='China').to_frame().T])

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387     9984670.0  0.913   America
France              63.951   2833687      640679.0  0.888    Europe
Germany             80.940   3874437      357114.0  0.916    Europe
Italy               60.665   2167744      301336.0  0.873    Europe
Japan              127.061   4602367      377930.0  0.891      Asia
United Kingdom      64.511   2950039      242495.0  0.907    Europe
United States      318.523  17348075     9525067.0  0.915   America
China                3.000         5           NaN    NaN       NaN

Creating Columns from other columns

In [163]:
df['GDP Per Capita'] = df['GDP'] / df['Population']
df

Population       GDP  Surface Area    HDI Continent  \
Canada              35.467   1785387       9984670  0.913   America   
France              63.951   2833687        640679  0.888    Europe   
Germany             80.940   3874437        357114  0.916    Europe   
Italy               60.665   2167744        301336  0.873    Europe   
Japan              127.061   4602367        377930  0.891      Asia   
United Kingdom      64.511   2950039        242495  0.907    Europe   
United States      318.523  17348075       9525067  0.915   America   

                GDP Per Capita  
Canada            50339.385908  
France            44310.284437  
Germany           47868.013343  
Italy             35733.025633  
Japan             36221.712406  
United Kingdom    45729.239975  
United States     54464.120330

Statistical info
